# Runs the whole test suite, with the test runner inside a container. This is ideal for CI.
services:
  test-runner:
    image: bittorrent-benchmarks:test
    container_name: test-runner
    volumes:
      - shared-volume:/opt/bittorrent-benchmarks/volume
    entrypoint: [ "bash", "-c", "/opt/bittorrent-benchmarks/docker/bin/run-tests.sh" ]
    healthcheck:
      test: stat /opt/bittorrent-benchmarks/volume/.initialized
      interval: 1s
      timeout: 5s
      retries: 150

  deluge-1:
    volumes: !override
      - type: volume
        source: shared-volume
        target: /var/lib/deluge
        volume:
          subpath: deluge-1
    depends_on:
      test-runner:
        condition: service_healthy

  deluge-2:
    volumes: !override
      - type: volume
        source: shared-volume
        target: /var/lib/deluge
        volume:
          subpath: deluge-2
    depends_on:
      test-runner:
        condition: service_healthy

  deluge-3:
    volumes: !override
      - type: volume
        source: shared-volume
        target: /var/lib/deluge
        volume:
          subpath: deluge-3
    depends_on:
      test-runner:
        condition: service_healthy

volumes:
  shared-volume:
