# Runs the whole test suite, with the test runner inside a container. This is ideal for CI.
services:
  test-runner:
    image: bittorrent-benchmarks:test
    container_name: test-runner
    entrypoint: [ "poetry", "run", "pytest", "--exitfirst" ]
    environment:
      - DELUGE_NODE_1=deluge-1
      - DELUGE_NODE_2=deluge-2
      - DELUGE_NODE_3=deluge-3
      - DELUGE_AGENT_1=http://agent-1:9001/
      - DELUGE_AGENT_2=http://agent-2:9002/
      - DELUGE_AGENT_3=http://agent-3:9003/
      - TRACKER_ANNOUNCE_URL=http://tracker:8000/announce
    depends_on:
      clean-volumes:
        condition: service_healthy
