apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deluge.pvc" . }}
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ include "storage.size" . }}