apiVersion: v1
kind: Service
metadata:
  name: deluge-service
  namespace: codex-benchmarks
  labels:
    app: deluge-nodes
spec:
  clusterIP: None
  selector:
    app: deluge-nodes
  ports:
    - port: 6890
      name: rpc
    - port: 6891
      name: listen-1
    - port: 6892
      name: listen-2