apiVersion: v1
kind: Service
metadata:
  name: tracker-service
  namespace: codex-benchmarks
  labels:
    app: tracker
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: tracker