apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittorrent-tracker
  namespace: codex-benchmarks
  labels:
    app: bittorrent-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bittorrent-tracker
  template:
    metadata:
      labels:
        app: bittorrent-tracker
    spec:
      containers:
      - name: tracker
        image: codexstorage/bittorrent-tracker
        ports:
        - containerPort: 8000
