experiment:
  networkSize: 10
  fileSize: "100MB"
  seeders: 4
  seederSets: 4
  repetitions: 10

  blockTTL: 360000
  blockMaintenanceInterval: 360000
  codexLogLevel: debug
  memory: "1Gi"

  # Experiments are ran as part of groups which may entail several invocations for this Helm chart.
  # We therefore identify both the experiment within a group, and the group itself.

  # Identifies the experiment within the group. If left empty, defaults to the release name.
  id: ""
  # Identifies the experiment group. Needs to be defined by the user.
  groupId: ""

  # If set to false, does not deploy a test runner (useful if you just want the network).
  testRunner: true

  # If set to false, does not delete the data at the end of each experiment. This is faster
  # than deleting it, but requires more space.
  removeData: true

deployment:
  appName: ""

  # If false, Codex nodes will not be allowed to run on the same node.
  allowColocation: true

  # Disables pulling of images and uses :minikube tag for the test runner, agents, and Codex.
  minikubeEnv: false

  # Allows overriding the tags for non-minikube images. This is useful when you're trying to
  # run the experiment in the cluster but off of a Codex or benchmark harness branch.
  runnerTag: "latest"
  nodeTag: "latest"

  # Labels for setting Deluge, tracker, and experiment runner node affinity towards pools.
  # Example:
  #   codexNodePool:
  #     workload: benchmarks
  codexNodePool: {}
  runnerNodePool: {}

  # Region in which to deploy machines. Leave empty to deploy to default.
  region: ""
