apiVersion: v1
kind: Service
metadata:
  name: deluge-nodes-service-{{ include "experiment.fullId" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: deluge-nodes-service
    {{- include "deluge-benchmarks.labels" . | nindent 4}}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: deluge-node
    {{- include "deluge-benchmarks.selectorLabels" . | nindent 4}}
  ports:
    - port: 6890
      name: rpc
    - port: 6891
      name: listen-1
    - port: 6892
      name: listen-2