apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deluge.pvc" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deluge-benchmarks.labels" . | nindent 4 }}

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ include "storage.size" . }}
  {{- if .Values.deployment.storageClass }}
  storageClassName: {{ .Values.deployment.storageClass }}
  {{- end }}