apiVersion: v1
kind: Service
metadata:
  name: deluge-nodes-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: deluge-nodes-{{ .Release.Name }}
    {{- include "deluge-benchmarks.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: deluge-nodes-{{ .Release.Name }}
  ports:
    - port: 6890
      name: rpc
    - port: 6891
      name: listen-1
    - port: 6892
      name: listen-2