{{- if .Values.experiment.testRunner }}
apiVersion: batch/v1
kind: Job
metadata:
  name: deluge-experiment-runner-{{ include "experiment.fullId" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: deluge-experiment-runner
    {{- include "deluge-benchmarks.labels" . | nindent 4 }}

spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: deluge-experiment-runner
        {{- include "deluge-benchmarks.labels" . | nindent 8 }}

    spec:
      {{- with .Values.deployment.runnerNodePool }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: deluge-experiment-runner
          image: {{ include "benchmark.harness.image" . }}
          imagePullPolicy: {{ include "benchmark.harness.imagePullPolicy" . }}
          args: [ "run", "deluge_experiment" ]
          env:
            - name: NETWORK_SIZE
              value: {{ .Values.experiment.networkSize | quote }}
            - name: SEEDERS
              value: {{ .Values.experiment.seeders | quote }}
            - name: REPETITIONS
              value: {{ .Values.experiment.repetitions | quote }}
            - name: SEEDER_SETS
              value: {{ .Values.experiment.seederSets | quote }}
            - name: FILE_SIZE
              value: {{ include "filesize.bytes" . | quote }}
            - name: TRACKER_ANNOUNCE_URL
              value: "http://bittorrent-tracker-service-{{ include "experiment.fullId" . }}.{{ .Release.Namespace }}.svc.cluster.local:8000/announce"
            - name: SHARED_VOLUME_PATH
              value: "/opt/bittorrent-benchmarks/volume"
            - name: DELUGE_STATEFULSET
              value: "deluge-nodes-{{ include "experiment.fullId" . }}"
            - name: DELUGE_SERVICE
              value: "deluge-nodes-service-{{ include "experiment.fullId" . }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: benchmark-volume
              mountPath: /opt/bittorrent-benchmarks/volume
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "2Gi"

      restartPolicy: Never

  backoffLimit: 0
{{- end }}