apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittorrent-tracker-{{ include "experiment.fullId" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: bittorrent-tracker
    {{- include "deluge-benchmarks.labels" . | nindent 4 }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: bittorrent-tracker
      {{- include "deluge-benchmarks.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        app.kubernetes.io/component: bittorrent-tracker
        {{- include "deluge-benchmarks.labels" . | nindent 8 }}
      annotations:
        {{- include "deluge-benchmarks.pod.annotations" . | nindent 8 }}

    spec:
      {{- with .Values.deployment.trackerNodePool }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: bittorrent-tracker
          image: codexstorage/bittorrent-tracker
          ports:
            - containerPort: 8000
