apiVersion: apps/v1
kind: Deployment
metadata:
  name: bittorrent-tracker-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bittorrent-tracker-{{ .Release.Name }}
    {{- include "deluge-benchmarks.labels" . | nindent 4 }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bittorrent-tracker-{{ .Release.Name }}
      {{- include "deluge-benchmarks.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        app: bittorrent-tracker-{{ .Release.Name }}
        {{- include "deluge-benchmarks.labels" . | nindent 8 }}

    spec:
      containers:
        - name: bittorrent-tracker-{{ .Release.Name }}
          image: codexstorage/bittorrent-tracker
          ports:
            - containerPort: 8000
