apiVersion: v1
kind: Service
metadata:
  name: bittorrent-tracker-service-{{ include "experiment.fullId" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bittorrent-tracker-service
    {{- include "deluge-benchmarks.labels" . | nindent 4 }}

spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: bittorrent-tracker
    {{- include "deluge-benchmarks.selectorLabels" . | nindent 4 }}