# We need a persistent volume for Vector to collect the logs, which will then be accessible
# to the log parser.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vector-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/vector-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
