name: Build Argo Workflows Runner Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  DOCKER_FILE: ./docker/bittorrent-benchmarks-workflows.Dockerfile
  DOCKER_REPO: codexstorage/bittorrent-benchmarks-workflows

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: false

  variables:
    name: Compute outputs
    needs: build-and-test
    runs-on: ubuntu-latest
    outputs:
      docker_file: ${{ env.DOCKER_FILE }}
      dockerhub_repo: ${{ env.DOCKER_REPO }}
    steps:
      - name: Dummy job
        if: false
        run: echo

  build-and-push:
    name: Build and Push
    needs: variables
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: ${{ needs.variables.outputs.docker_file }}
      dockerhub_repo: ${{ needs.variables.outputs.dockerhub_repo }}
    secrets: inherit
