name: Test and Build

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  DOCKER_FILE: bittorrent-benchmarks.Dockerfile
  DOCKER_REPO: codexstorage/bittorrent-benchmarks

jobs:
  test-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REPO }}
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build Test Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: false
          load: true
          tags: bittorrent-benchmarks:test
          build-args: |
            BUILD_TYPE=test

      - name: Type Check
        run: |
          docker run --rm --entrypoint mypy bittorrent-benchmarks:test .

      - name: Run Unit Tests
        run: |
          docker run --rm --entrypoint pytest bittorrent-benchmarks:test -m "not integration"

      - name: Build and Push Prod. Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: bittorrent-benchmarks:latest
          labels: ${{ steps.meta.outputs.labels }}