apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deluge-benchmark-
spec:
  serviceAccountName: codex-benchmarks-workflows
  entrypoint: benchmark-workflow
  arguments:
    parameters:
      - name: repetitions
        value: 1
      - name: fileSize
        value: '["100MB", "200MB"]'
      - name: constrained__networkSize_seeders
        value: "[[5, [1, 2]], [10, [1, 3, 5]], [20, [1, 6, 10]]]"
      - name: seederSets
        value: 1
      - name: maxExperimentDuration
        value: 72h

  templates:
    - name: benchmark-workflow
      parallelism: 1
      steps:
        - - name: expand-parameter-matrix
            template: expand-parameter-matrix

        - - name: benchmark-experiment
            template: benchmark-experiment
            hooks:
              exit:
                template: cleanup
                arguments:
                  parameters:
                    - name: runId
                      value: "{{item.runId}}"
            arguments:
              parameters:
                - name: runId
                  value: "{{item.runId}}"
                - name: fileSize
                  value: "{{item.fileSize}}"
                - name: seederSets
                  value: "{{item.seederSets}}"
                - name: networkSize
                  value: "{{item.networkSize}}"
                - name: seeders
                  value: "{{item.seeders}}"
                - name: repetitions
                  value: "{{item.repetitions}}"

            withParam: "{{steps.expand-parameter-matrix.outputs.result}}"

    - name: benchmark-experiment
      inputs:
        parameters:
          - name: runId
          - name: fileSize
          - name: seederSets
          - name: networkSize
          - name: seeders
          - name: repetitions

      steps:
        - - name: deploy-experiment
            template: deploy-experiment
            arguments:
              parameters:
                - name: runId
                  value: "{{inputs.parameters.runId}}"
                - name: fileSize
                  value: "{{inputs.parameters.fileSize}}"
                - name: seederSets
                  value: "{{inputs.parameters.seederSets}}"
                - name: networkSize
                  value: "{{inputs.parameters.networkSize}}"
                - name: seeders
                  value: "{{inputs.parameters.seeders}}"
                - name: repetitions
                  value: "{{inputs.parameters.repetitions}}"

        - - name: wait-for-test-start
            template: wait-for-test-start
            arguments:
              parameters:
                - name: runId
                  value: "{{inputs.parameters.runId}}"

        - - name: wait-for-test-completion
            template: wait-for-test-completion
            arguments:
              parameters:
                - name: runId
                  value: "{{inputs.parameters.runId}}"

    - name: expand-parameter-matrix
      script:
        image: codexstorage/bittorrent-benchmarks-workflows:latest
        command: [ "python", "-m", "parameter_expander" ]
        args:
          - "{{ workflow.parameters.json }}"

    - name: deploy-experiment
      inputs:
        parameters:
          - name: runId
          - name: fileSize
          - name: seederSets
          - name: networkSize
          - name: seeders
          - name: repetitions

      script:
        image: codexstorage/bittorrent-benchmarks-workflows:latest
        command: [ "/bin/bash" ]
        source: |
          helm install e{{inputs.parameters.runId}} ./k8s/charts/deluge\
            --namespace codex-benchmarks\
            --set experiment.repetitions={{inputs.parameters.repetitions}}\
            --set experiment.fileSize={{inputs.parameters.fileSize}}\
            --set experiment.networkSize={{inputs.parameters.networkSize}}\
            --set experiment.seeders={{inputs.parameters.seeders}}\
            --set experiment.seederSets={{inputs.parameters.seederSets}}

    - name: wait-for-test-start
      inputs:
        parameters:
          - name: runId
      script:
        image: codexstorage/bittorrent-benchmarks-workflows:latest
        command: [ "/bin/bash" ]
        source: |
          kubectl wait -n codex-benchmarks\
            --for=condition=Ready\
            --selector=app=deluge-e{{inputs.parameters.runId}}-testrunner\
            --timeout=300s\
            pod

    - name: wait-for-test-completion
      inputs:
        parameters:
          - name: runId
      script:
        image: codexstorage/bittorrent-benchmarks-workflows:latest
        command: [ "/bin/bash" ]
        source: |
          ./docker/bin/kubectl-wait-job\
            --selector=app=deluge-e{{inputs.parameters.runId}}-testrunner\
            --timeout={{workflow.parameters.maxExperimentDuration}}\
            -n codex-benchmarks

    - name: cleanup
      inputs:
        parameters:
          - name: runId
      script:
        image: codexstorage/bittorrent-benchmarks-workflows:latest
        command: [ "/bin/bash" ]
        source: |
          helm uninstall e{{inputs.parameters.runId}} -n codex-benchmarks
      
